#!groovy
def statuscolor = { currentBuild ->
  def status = "good"
  if (currentBuild.previousBuild != "SUCCESS") {
    if (currentBuild.result == "UNSTABLE") {
      status = "warning"
    }
    if (currentBuild.result == "FAILURE") {
      status = "danger"
    }
  }
  status
}
node {
  withEnv(['JAVA_HOME=/opt/java','PATH+EXTRA=/usr/local/bin:/opt/ant/bin']) {
    stage("Environment") {
      sh 'echo $PATH'
      sh 'java -version'
      sh 'mvn -version'
    }
    stage('Checkout WPQATools') {
      checkout scm
    }
    stage('Run Tests') {
        dir('automation') {
            sh 'mvn -DVISIBLE=false -DsuiteXmlFile=${wp_suite}.xml -DTESTRAIL=${wp_run} -DENV=${wp_env} clean compile test'
        }
    }
  }
}
